### ISSUE TITLE
boot with bin file?

### ISSUE THREAD

**Issue by killeradhil** [voltflake/os#1]
machine2002@debian:~/os/build$ ls -l
\total 56
-rw-r--r-- 1 machine2002 machine2002  1696 Jan  8 17:55 bootloader.o
-rwxr-xr-x 1 machine2002 machine2002 32359 Jan  8 17:57 kernel.bin
-rwxr-xr-x 1 machine2002 machine2002  9032 Jan  8 17:57 kernel.o
-rw-r--r-- 1 machine2002 machine2002   776 Jan  8 17:56 kmain.o
-rw-r--r-- 1 machine2002 machine2002   291 Jan  8 17:55 linker.ld
machine2002@debian:~/os/build$ \
### 
sir how i load into my usb stick?

**Comment by voltflake** [comment]
I did it a long time ago on linux. Give me some time to get it working on windows and I'll help you out!

**Comment by voltflake** [comment]
Windows
---
Selecting right USB stick and `kernel.bin` file in [Rufus](https://rufus.ie/en/) did the job fine  

Linux
---
This command should do the trick but i haven't tested it. Make sure you have right partition selected in output file (`of`) parameter. Partition should be formatted in fat32.  
```
dd if=kernel.bin of=/dev/sdb1
```
Make sure MBR booting is supported/enabled on your PC/Laptop. If it's UEFI system turn on compatibility Support Module (CSM) setting in BIOS. It may have different name like "legacy boot" or something.

It's always a better idea to test this stuff in virtual machines and emulation tools.

Let me know if this info helped. Good luck!

**Comment by killeradhil** [comment]
i try with rufus.but rufus cant load kernel.bin "no bootable or unsupported format".
here is the hexdump of kernal.bin.
![kernelbin](https://user-images.githubusercontent.com/67538923/211244111-c3c766e6-832b-460a-bb60-29812ad5dfe1.png)

**Comment by killeradhil** [comment]
i try with rufus.but rufus cant load kernel.bin "no bootable or unsupported format".
here is the hexdump of kernal.bin.
![kernelbin](https://user-images.githubusercontent.com/67538923/211244111-c3c766e6-832b-460a-bb60-29812ad5dfe1.png)dd if=kernel.bin of=/dev/sdb1 command moves the bin to drive
result pc cant boot from kernal.bin,no screen output,

**Comment by voltflake** [comment]
There is something wrong when linking your binary. First 512 bytes of binary should be assembly block labeled as bootloader.

And last two bytes of first 512 byte block should contain magic number (MBR boot signature) 0x55AA.

Examine your kernel.o file with objdump tool and look for sections which contain that "Hello world" string. Once you find name of that section place it somewhere at the bottom of binary in linking script.

**Comment by voltflake** [comment]
I updated linker script to support .rodata-prefixed sections, check if it helps you.  
If you plan to add more complex C code make sure it links correctly because my linker script kinda sucks.

**Comment by killeradhil** [comment]
thanks sir now working:) thank to modify,
