### ISSUE TITLE
cant run boot from hardware

### ISSUE THREAD

**Issue by killeradhil** [voltflake/os#2]
sir it perfectly runs in qemu, after you modified, but did not run in pc.
i notice bios only read '0'lba block only and exit. then go to hard drive os.

**Comment by voltflake** [comment]
Runs fine on my PC. Can you hexdump your binary here so I can see if it's good?  
PC should read first LBA block and load it into 0x7C00 memory address. Then assembly code uses BIOS functions to load other blocks into memory and jump to 32bit mode.

**Comment by voltflake** [comment]
Not sure if it's available on Linux, but you can [make an .vdmk image of your USB stick with virtualbox](https://www.how2shout.com/how-to/virtualbox-virtual-machine-boot-usb.html) and try to boot it in virtualbox. If it doesn't work with that image but works in QEMU than it means you made something wrong when writing to USB stick. If it does work than problem is on PC/BIOS side. Maybe it tries to load it onto another address or you have UEFI boot enabled... I don't know.

**Comment by killeradhil** [comment]
here is my thumb drive first 51kb image
[osimg.txt](https://github.com/voltflake/os/files/10375288/osimg.txt)
rename in .img format.

**Comment by killeradhil** [comment]
And i run 51kb osimg file form thumbdrive  then load that img file into qemu it works fine.

So as you mentioned os looks good.

So what settings should i change, and what setting should n't change.

**Comment by voltflake** [comment]
What model/manufacturer your laptop/pc is?  
Your image worked fine on my PC.

**Comment by killeradhil** [comment]
I had 2 laptops both of them failed to boot thumb drive.

I opened bios settings one laptop had both[uefi/legesy]
But preference to bios legacy first.

Laptop 2 had only boot from legacy. 

But Both of them failed.

Is slow drive cause boot issue
My drive is 0.3kb/sec😁😂 yes realy.

**Comment by killeradhil** [comment]
In live run both laptops read lba 0 from drive then exit read  and go to hard drive to boot.

**Comment by killeradhil** [comment]
> What model/manufacturer your laptop/pc is?  
> Your image worked fine on my PC.

Model= Hp probook6455b 
Model =lenovob490

**Comment by voltflake** [comment]
> In live run both laptops read lba 0 from drive then exit read and go to hard drive to boot.

How do you know they read it?

**Comment by killeradhil** [comment]
> > In live run both laptops read lba 0 from drive then exit read and go to hard drive to boot.
> 
> How do you know they read it?

I create that usb thumb drive from pi pico and attach 8mb flash to it. Making this as mass storage. 

Debug it on live run by uart output

**Comment by killeradhil** [comment]
so i can see what pc did in live

**Comment by voltflake** [comment]
Have you tested with simple USB thumbdrive, without raspberry pi? Preferably on usb 2.0 or older slot if you have.

**Comment by killeradhil** [comment]
> Have you tested with simple USB thumbdrive, without raspberry pi? Preferably on usb 2.0 or older slot if you have.

Ok sir i will try it.

**Comment by voltflake** [comment]
I noticed my bootloader code is a little non-standard so i'll try to rewrite it in a way that is more recommended by [OSdev MBR guide](https://wiki.osdev.org/MBR_(x86)).

**Comment by voltflake** [comment]
Found laptop with same issue as you experiencing. I managed to make some progress but it still requires more debugging. It successfully boots to real mode now. Hopefully tomorrow I'll fix everything to make it work in protected mode.

**Comment by voltflake** [comment]
I [updated bootloader](https://github.com/voltflake/os/commit/27a56658aced46e6296b181bff4a9aff6c80dff9) so it should work fine now.

Issue was that I created bootloader with assumption that it will be stored on floppy drive. On floppy MBR spec allows using 510 of 512 sector bytes as bootstrap code space and it worked great on my devices. Unfortunately this is not a case for all devices, many manufacturers program BIOS to display device with MBR record and then, when trying to boot from it checks if it contains partition entries and if it doesn't - it **SKIPS THIS DEVICE** and continues to next boot medium. Plus to all this stuff if a device doesn't contain exactly one active partition entry (there could be up to 4 partitions), BIOS just skips it too.

SEE: [Figure 2. Anatomy of the MBR](https://developer.ibm.com/articles/l-linuxboot/)

I think this is dumb from BIOS side to check for partition tables if first sector already has all the bootstrapping code with MBR signature. Plus it even could be dummy partition with like 1 sector in size so those checks are basically useless and add pain to developers, but whatever.

This was hard to debug and I haven't found any info on internet that highlights this thing. Hope it helps with your issue.

**Comment by killeradhil** [comment]
it works bro thanks.
